title: Xingyan Wang # your name (or website title) here
logo: "/images/cute.jpeg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D. Candidate in Biostatistics
  <br><br>
  Penn State College of Medicine 
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://dajiangliu.blog">Dr. Dajiang Liu's Lab</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
